### ISSUE TITLE
Filler Block caused crash:  Encountered an unexpected exception net.minecraft.class_148: Ticking block entity

### ISSUE THREAD

**Issue by Pib-k** [Kotori316/QuarryPlus#456]
## Describe the bug

Filler worked fine placing sandstone slabs. Suddenly my minecraft world crashed. Removing the QuarryPlus mod stopped the crashing. Also deleting the specific filler machine active using Amulet Editor fixed the crashes. 

Edit: After doing some testing, this crash happens when choosing an area which already has slabs partly placed.

![2024-07-16_18 26 25](https://github.com/user-attachments/assets/ceda1f52-5fe6-4273-930e-62d22da07aae)

If you start this filler (filled with slabs of the same type!) it will crash when it reaches an already placed slab

## If your server/client has crashed, please give me the crash report.

https://pastebin.com/wCb9f3c6

**Comment by Kotori316** [comment]
I'll take a look

**Comment by Kotori316** [comment]
Confirmed

**Comment by Kotori316** [comment]
Fixed in the latest release. Thank you for your report.

**Comment by AoSankaku** [comment]
Still occurs on 1.20.1 when placing stone slab:

Entire log: https://mclo.gs/iWmiGNR
Crash report: https://mclo.gs/6iSa1rW
Suspected part: Spam of 
```
at net.minecraft.world.level.block.SlabBlock.m_6864_(SlabBlock.java:85) ~[server-1.20.1-20230612.114412-srg.jar%23649!/:?]at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60629_(BlockBehaviour.java:802) ~[server-1.20.1-20230612.114412-srg.jar%23649!/:?]at net.minecraft.world.item.context.DirectionalPlaceContext.m_7059_(DirectionalPlaceContext.java:27) ~[server-1.20.1-20230612.114412-srg.jar%23649!/:?]
```

Note: may be ferritecore's fault, but there's no reports on issues
